development:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  # adapter: redis
  # port: 6379
  # #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: redis://54.64.74.19:6379
  # channel_prefix: chokichoki_production
